postgres:
  host: localhost
  port: 5433
  user: metric
  password: metric
  database: metric
redis:
  host: localhost
  port: 6379
kafka:
  host: localhost
  port: 9092
  topic_temperature: temperature
  topic_events: events
receiver:
  host: localhost
  port: 8080
accessor:
  host: localhost
  port: 8081