version: '3.1'

services: 
  postgres:
    image: postgres
    restart: always
    environment:
        - POSTGRES_PASSWORD=metric
        - POSTGRES_USER=metric
        - POSTGRES_DB=metric
    ports:
        - "5433:5432"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
        - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
        - "9092:9092"
    environment:
        - KAFKA_ADVERTISED_HOST_NAME=kafka
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
        - KAFKA_CREATE_TOPICS="events:3:3,temperature:3:3"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - zookeeper
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
  saver:
    image: com.metric.saver
    depends_on:
        - postgres
        - kafka
  receiver:
    image: com.metric.receiver
    ports:
        - "8080:8080"
    depends_on:
        - kafka
  processor:
    image: com.metric.processor
    depends_on:
        - kafka
        - redis
  accessor:
    image: com.metric.assessor
    ports:
        - "8081:8080"
    depends_on:
      - postgres
